# Generated by Django 5.2.3 on 2026-03-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('extracted_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('verdict', models.CharField(blank=True, choices=[('SUPPORTED', 'Supported'), ('PARTIAL', 'Partially Supported'), ('UNSUPPORTED', 'Unsupported')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('runtime_ms', models.IntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='verifier.document')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('chunk_text', models.TextField()),
                ('similarity_score', models.FloatField()),
                ('entailment', models.FloatField(blank=True, null=True)),
                ('neutral', models.FloatField(blank=True, null=True)),
                ('contradiction', models.FloatField(blank=True, null=True)),
                ('is_best', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='verifier.evaluationrun')),
            ],
        ),
    ]
