# Generated by Django 5.2.3 on 2026-03-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entailment', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('contradiction', models.FloatField(default=0.0)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nli', to='verifier.evidencechunk')),
            ],
        ),
    ]
