# Generated by Django 5.2.3 on 2026-03-25 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_nliresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrun',
            name='comparison_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
