# Generated by Django 5.2.3 on 2026-03-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0003_evaluationrun_comparison_id_evaluationrun_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencechunk',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
