# Generated by Django 5.2.3 on 2026-03-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0004_evidencechunk_source_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_entailment', models.FloatField(default=0.0)),
                ('avg_entailment', models.FloatField(default=0.0)),
                ('avg_contradiction', models.FloatField(default=0.0)),
                ('best_similarity', models.FloatField(default=0.0)),
                ('risk_percentage', models.IntegerField(default=100)),
                ('evidence_count', models.IntegerField(default=0)),
                ('support_count', models.IntegerField(default=0)),
                ('contradiction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='verifier.evaluationrun')),
            ],
        ),
    ]
