# Generated by Django 5.2.3 on 2026-03-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0005_runmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmetric',
            name='ragas_answer_relevancy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runmetric',
            name='ragas_faithfulness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
