# Generated by Django 5.2.3 on 2026-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0006_runmetric_ragas_answer_relevancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmetric',
            name='deepeval_answer_relevancy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runmetric',
            name='deepeval_faithfulness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
