# Generated by Django 5.2.3 on 2026-03-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0007_runmetric_deepeval_answer_relevancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmetric',
            name='final_verdict',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='runmetric',
            name='trust_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
