# Generated by Django 5.2.3 on 2026-03-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0008_runmetric_final_verdict_runmetric_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmetric',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
